language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker-compose -f docker-compose-build.yaml build --parallel
  - docker tag reverseproxy utsanonymous/reverseproxy:v1
  - docker tag udagram-frontend utsanonymous/udagram-frontend:v1
  - docker tag udagram-api-feed utsanonymous/udagram-api-feed:v1
  - docker tag udagram-api-user utsanonymous/udagram-api-user:v1

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push utsanonymous/reverseproxy:v1
  - docker push utsanonymous/udagram-frontend:v1
  - docker push utsanonymous/udagram-api-feed:v1
  - docker push utsanonymous/udagram-api-user:v1
